on:
  pull_request:
    branches:
      - master

jobs:
  add_todo_list:
    runs-on: ubuntu-latest
    name: Add release todo-list
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: 'Comment PR'
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
              github.issues.createComment({
                            issue_number, owner, repo,
                            body: '
                  Todos before releasing a new version \n \n
                  - [ ] Check release notes: All new features/changes included? \n
                  - [ ] Check help messages: Are they all up to date? Update screenshots. Is the date correct? \n
                  - [ ] Check preview build and test it with the productive database.'});


      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "

          "
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
