on:
  pull_request:
    branches:
      - master

jobs:
  add_todo_list:
    runs-on: ubuntu-latest
    name: Add release todo-list
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "

          Todos before releasing a new version

          [ ] Check release notes: All new features/changes included?
          [ ] Check help messages: Are they all up to date? Update screenshots. Is the date correct?
          [ ] Check preview build and test it with the productive database.

          "
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
